// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameToken = "tokens"

// Token mapped from table <tokens>
type Token struct {
	TokenID   int32     `gorm:"column:token_id;primaryKey;autoIncrement:true" json:"token_id"`
	UserID    int32     `gorm:"column:user_id" json:"user_id"`
	Token     string    `gorm:"column:token;not null" json:"token"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	ExpiredAt time.Time `gorm:"column:expired_at" json:"expired_at"`
}

// TableName Token's table name
func (*Token) TableName() string {
	return TableNameToken
}
