// Code generated by Kitex v0.11.3. DO NOT EDIT.

package paymentservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	payment "github.com/renxingdawang/rxdw-mall/server/shared/kitex_gen/payment"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Charge": kitex.NewMethodInfo(
		chargeHandler,
		newPaymentServiceChargeArgs,
		newPaymentServiceChargeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CancelPayment": kitex.NewMethodInfo(
		cancelPaymentHandler,
		newPaymentServiceCancelPaymentArgs,
		newPaymentServiceCancelPaymentResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"TimedCancelPayment": kitex.NewMethodInfo(
		timedCancelPaymentHandler,
		newPaymentServiceTimedCancelPaymentArgs,
		newPaymentServiceTimedCancelPaymentResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	paymentServiceServiceInfo                = NewServiceInfo()
	paymentServiceServiceInfoForClient       = NewServiceInfoForClient()
	paymentServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return paymentServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return paymentServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return paymentServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "PaymentService"
	handlerType := (*payment.PaymentService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "payment",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.11.3",
		Extra:           extra,
	}
	return svcInfo
}

func chargeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*payment.PaymentServiceChargeArgs)
	realResult := result.(*payment.PaymentServiceChargeResult)
	success, err := handler.(payment.PaymentService).Charge(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPaymentServiceChargeArgs() interface{} {
	return payment.NewPaymentServiceChargeArgs()
}

func newPaymentServiceChargeResult() interface{} {
	return payment.NewPaymentServiceChargeResult()
}

func cancelPaymentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*payment.PaymentServiceCancelPaymentArgs)
	realResult := result.(*payment.PaymentServiceCancelPaymentResult)
	success, err := handler.(payment.PaymentService).CancelPayment(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPaymentServiceCancelPaymentArgs() interface{} {
	return payment.NewPaymentServiceCancelPaymentArgs()
}

func newPaymentServiceCancelPaymentResult() interface{} {
	return payment.NewPaymentServiceCancelPaymentResult()
}

func timedCancelPaymentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*payment.PaymentServiceTimedCancelPaymentArgs)
	realResult := result.(*payment.PaymentServiceTimedCancelPaymentResult)
	success, err := handler.(payment.PaymentService).TimedCancelPayment(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPaymentServiceTimedCancelPaymentArgs() interface{} {
	return payment.NewPaymentServiceTimedCancelPaymentArgs()
}

func newPaymentServiceTimedCancelPaymentResult() interface{} {
	return payment.NewPaymentServiceTimedCancelPaymentResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Charge(ctx context.Context, req *payment.ChargeReq) (r *payment.ChargeResp, err error) {
	var _args payment.PaymentServiceChargeArgs
	_args.Req = req
	var _result payment.PaymentServiceChargeResult
	if err = p.c.Call(ctx, "Charge", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CancelPayment(ctx context.Context, req *payment.CancelPaymentReq) (r *payment.CancelPaymentResp, err error) {
	var _args payment.PaymentServiceCancelPaymentArgs
	_args.Req = req
	var _result payment.PaymentServiceCancelPaymentResult
	if err = p.c.Call(ctx, "CancelPayment", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) TimedCancelPayment(ctx context.Context, req *payment.TimedCancelPaymentReq) (r *payment.TimedCancelPaymentResp, err error) {
	var _args payment.PaymentServiceTimedCancelPaymentArgs
	_args.Req = req
	var _result payment.PaymentServiceTimedCancelPaymentResult
	if err = p.c.Call(ctx, "TimedCancelPayment", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
